### ISSUE TITLE
TypeError: Service[this.service] is not a constructor

### ISSUE THREAD

**Issue by kinga17** [staromeste/homebridge-http-advanced-accessory#40]
I am getting the following when Homebridge attempts to initialize the plugin:

TypeError: Service[this.service] is not a constructor
    at HttpAdvancedAccessory.getServices (/usr/lib/node_modules/homebridge-http-advanced-accessory/index.js:286:20)
    at BridgeService.createHAPAccessory (/usr/lib/node_modules/homebridge/src/bridgeService.ts:461:41)
    at /usr/lib/node_modules/homebridge/src/server.ts:353:44
    at Array.forEach (<anonymous>)
    at Server.loadAccessories (/usr/lib/node_modules/homebridge/src/server.ts:270:29)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:162:12)

I am not familiar with coding in Typescript, so I do not know how to diagnose this issue.

**Comment by skarndev** [comment]
Getting exactly the same error. Any solution?
